connections {
  ipsec-bench {
    version = 2
    remote_addrs = <B_PUBLIC_IP>
    proposals = aes128gcm16-prfsha256-ecp256

    local {
      auth = psk
      id = <A_PUBLIC_IP>
    }
    remote {
      auth = psk
      id = <B_PUBLIC_IP>
    }

    children {
      bench {
        mode = tunnel
        local_ts  = 10.254.0.1/32
        remote_ts = 10.254.0.2/32
        esp_proposals = aes128gcm16-ecp256
        start_action = start
      }
    }
  }
}

secrets {
  ike-psk {
    id-a = <A_PUBLIC_IP>
    id-b = <B_PUBLIC_IP>
    secret = "PSK_HERE"
  }
}